#!/bin/bash

yum -y install nagios            #install,start and enable nagios
systemctl enable nagios
systemctl start nagios

setenforce 0                     # turn off SElinux, so it doesnt trip us up
sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config/ #Disable it permanently

systemctl enable httpd           #enable and start apache
systemctl start httpd 

yum -y install nrpe              # install,enable  and start nrpe, the nagios client
systemctl enable nrpe
systemctl start nrpe
yum -y install nagios-plugins-all
yum -y install nagios-plugins-nrpe

htpasswd -b /etc/nagios/passwd nagiosadmin nagiosadmin      #set the nagios admin password
sed -i 's,allowed_hosts=127.0.0.1,allowed_hosts=127.0.0.1\,10.128.0.0\/20,g' /etc/nagios/nrpe.cfg
# The above enables connections from your subnet,please,please adjust to be your subnet!

sed -i 's,dont_blame_nrpe=0,dont_blame_nrpe=1,g' /etc/nagios/nrpe.cfg
#enable NRPE monitoring

mkdir /etc/nagios/servers
#create a directory for our server configuration and enable it in the config file
sed -i's, #cfg_dir=/etc/nagios/servers,cfg_dir=/etc/nagios/servers,g' /etc/nagios/nagios.cfg
echo 'define command{
                     
                     command_name check_nrpe  
